[package]
name = "toolbox"
version = "0.1.0"
edition = "2021"

[dependencies]
motif-core = { path = "../../packages/core" }
motif-event-sdk = { path = "../../packages/event-sdk" }
motif-observer = { path = "../../packages/observer" }

tokio = { workspace = true, features = ["full"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
async-nats = "0.50"
sqlx.workspace = true
futures = "0.3.31"
axum.workspace = true
tower-http.workspace = true
