"use client"

import Link from "next/link"
import { useState } from "react"
import { ArrowLeft, Captions, Check, ChevronDown, CirclePlay, Download, Ellipsis, Film, ImageIcon, Music2, Pause, Play, Redo2, Scissors, Send, Sparkles, Undo2, Upload, Volume2, WandSparkles } from "lucide-react"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"

const media = [
 { name:"Açılış_Kancası.mp4", time:"00:18", image:"https://images.unsplash.com/photo-1589903308904-1010c2294adc?auto=format&fit=crop&w=600&q=80" },
 { name:"Derin_Sohbet.mp4", time:"01:05", image:"https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=600&q=80" },
 { name:"Sıcak_Konu.mp4", time:"00:47", image:"https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=600&q=80" },
 { name:"İzleyici_Soruları.mp4", time:"10:18", image:"https://images.unsplash.com/photo-1581368135153-a506cf13b1e1?auto=format&fit=crop&w=600&q=80" },
 { name:"Ana_Fikir.mp4", time:"00:41", image:"https://images.unsplash.com/photo-1593697821252-0c9137d9fc45?auto=format&fit=crop&w=600&q=80" },
]

function EditorNav(){return <header className="flex h-16 shrink-0 items-center justify-between border-b bg-card px-3 md:px-5"><div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="icon" render={<Link href="/videos" />} aria-label="Videolara dön"><ArrowLeft/></Button><div className="min-w-0"><p className="truncate text-sm font-medium">Podcast Highlight 03</p><p className="hidden text-[11px] text-muted-foreground sm:block">Son kayıt az önce</p></div></div><div className="hidden items-center gap-1 md:flex"><Button variant="ghost" size="icon" aria-label="Geri al"><Undo2/></Button><Button variant="ghost" size="icon" aria-label="İleri al"><Redo2/></Button><Button variant="ghost" size="sm">%100 <ChevronDown data-icon="inline-end"/></Button><Button variant="secondary" size="icon" aria-label="Seçim aracı"><Sparkles/></Button></div><div className="flex items-center gap-2"><div className="hidden -space-x-2 sm:flex"><Avatar className="size-8 border-2 border-card"><AvatarFallback>AY</AvatarFallback></Avatar><Avatar className="size-8 border-2 border-card"><AvatarFallback>MK</AvatarFallback></Avatar></div><Button variant="outline" className="hidden sm:flex"><Play data-icon="inline-start"/> Önizle</Button><Button><Download data-icon="inline-start"/> Dışa aktar</Button></div></header>}

function MediaLibrary(){return <Card className="min-h-0"><CardHeader className="border-b"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><CardTitle>Medya kütüphanesi</CardTitle><p className="text-xs text-muted-foreground">Projeye eklenen kaynak dosyaları</p></div><div className="flex items-center gap-2"><Tabs defaultValue="media"><TabsList><TabsTrigger value="ses"><Music2/> Ses</TabsTrigger><TabsTrigger value="media"><ImageIcon/> Medya</TabsTrigger><TabsTrigger value="efekt"><WandSparkles/> Efekt</TabsTrigger></TabsList></Tabs><Button size="sm"><Upload data-icon="inline-start"/> İçe aktar</Button></div></div></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3 lg:grid-cols-5">{media.map(item=><button key={item.name} className="group flex min-w-0 flex-col gap-2 text-left"><span className="relative aspect-video overflow-hidden rounded-lg border bg-muted"><img src={item.image} alt="Podcast stüdyosu video karesi" className="size-full object-cover opacity-80 transition-transform group-hover:scale-105"/><span className="absolute inset-0 flex items-center justify-center opacity-0 transition-opacity group-hover:opacity-100"><CirclePlay className="size-8"/></span><Badge className="absolute bottom-1 right-1" variant="secondary">{item.time}</Badge></span><span className="truncate text-xs">{item.name}</span></button>)}</CardContent></Card>}

function EnhancePanel(){return <Card className="min-h-0"><CardHeader className="border-b"><div className="flex items-center justify-between"><CardTitle className="flex items-center gap-2"><WandSparkles className="size-4 text-primary"/> Geliştir</CardTitle><Button variant="ghost" size="icon" aria-label="Daha fazla"><Ellipsis/></Button></div></CardHeader><CardContent className="flex flex-col gap-5 overflow-auto"><div className="flex flex-col gap-2"><p className="text-sm font-medium">Klip iyileştirme</p><div className="flex items-end justify-between"><span className="text-xl font-semibold">%72</span><span className="text-[11px] text-muted-foreground">3 geliştirme uygulandı</span></div><Progress value={72}/></div><ul className="flex flex-col gap-2 text-xs"><li className="flex justify-between">Arka plan gürültüsünü kaldır <Check className="size-4 text-success"/></li><li className="flex justify-between">Ses seviyelerini dengele <Check className="size-4 text-success"/></li><li className="flex justify-between">Sessiz boşlukları kısalt <Check className="size-4 text-success"/></li><li className="flex justify-between text-muted-foreground">Temponun akışını iyileştir <span>○</span></li></ul><div className="flex flex-col gap-3"><p className="text-xs text-muted-foreground">Önerilen iyileştirmeler</p>{[{title:"Kancayı güçlendir",desc:"İlk 3 saniyeyi daha etkili yap",action:"Güçlendir"},{title:"Sessizliği kaldır",desc:"Daha akıcı bir tempo oluştur",action:"Kısalt"}].map(x=><div key={x.title} className="rounded-lg border bg-background p-3"><div className="flex items-start gap-3"><div className="flex size-8 items-center justify-center rounded-md bg-primary text-primary-foreground"><Sparkles className="size-4"/></div><div className="min-w-0 flex-1"><p className="text-xs font-medium">{x.title}</p><p className="text-[11px] text-muted-foreground">{x.desc}</p></div></div><div className="mt-3 flex items-center justify-between"><span className="text-[10px] text-muted-foreground">00:00 — 00:08</span><Button size="xs">{x.action}</Button></div></div>)}</div><div className="mt-auto flex flex-wrap gap-2"><Badge variant="outline"><Scissors/> Akıllı kesim</Badge><Badge variant="outline"><Captions/> Otomatik altyazı</Badge></div><div className="flex items-center gap-2 rounded-lg border bg-background p-2"><input className="min-w-0 flex-1 bg-transparent text-xs outline-none" placeholder="Neyi düzeltelim?" aria-label="Düzeltme isteği"/><Button size="icon-xs" aria-label="Gönder"><Send/></Button></div></CardContent></Card>}

export function VideoDetailView(){const [playing,setPlaying]=useState(false);return <div className="flex h-dvh min-w-[680px] flex-col overflow-hidden bg-background"><EditorNav/><main className="grid min-h-0 flex-1 grid-cols-[minmax(0,1fr)_260px] gap-3 p-3 xl:grid-cols-[minmax(0,1fr)_300px]"><section className="grid min-h-0 grid-rows-[minmax(300px,1.25fr)_minmax(230px,.75fr)] gap-3"><Card className="panel-grid min-h-0"><CardContent className="flex min-h-0 flex-1 items-center justify-center p-4"><div className="relative h-full max-h-[500px] aspect-[9/16] overflow-hidden rounded-xl border bg-muted"><img src="https://images.unsplash.com/photo-1593697909683-bccb1b9e68a4?auto=format&fit=crop&w=800&q=85" alt="Podcast kaydında konuşan sunucu" className="size-full object-cover"/><button onClick={()=>setPlaying(!playing)} className="absolute inset-0 flex items-center justify-center bg-background/10" aria-label={playing?"Duraklat":"Oynat"}>{playing?<Pause className="size-12 drop-shadow-lg"/>:<Play className="size-12 drop-shadow-lg"/>}</button><div className="absolute inset-x-3 bottom-3 rounded-lg border bg-background/85 p-3 backdrop-blur"><div className="mb-2 flex items-center justify-between text-[10px]"><span>01:21</span><span>03:18</span></div><Progress value={42}/><div className="mt-2 flex justify-between"><Volume2 className="size-4"/><span className="text-[10px] text-muted-foreground">Podcast Highlight 03</span><Film className="size-4"/></div></div></div></CardContent></Card><MediaLibrary/></section><EnhancePanel/></main></div>}
